language: php
cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
    - "$HOME/.selenium/cache"
    
php:
  - 5.6
  - 7.0
  - 7.1
env:
  - VERSION=8.x-1.x-test
  
sudo: required
dist: trusty

addons:  
  firefox: 46.0.1
  apt:
    packages:
      - xorg
      - xvfb
      - dbus-x11
      - x11-xkb-utils
      - xfonts-100dpi
      - xfonts-75dpi
      - xfonts-scalable
      - xserver-xorg-core
  
mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - composer self-update
  - composer --version
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
   
  # Configure the display.
  - export DISPLAY=:0
  - sh -e /etc/init.d/xvfb start
  - Xvfb :0 -ac -screen 0 1366x768x24 &
  - sleep 3 # give xvfb some time to start
  
  # Run selenium standalone server.
  - SELENIUM="$HOME/.selenium/cache/selenium-server-standalone-2.53.1.jar";
  - if [[ ! -f $SELENIUM ]]; then wget -O $SELENIUM http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar; fi
  - java -jar $SELENIUM -port 4444 > /dev/null 2>&1 &
  - echo "[  OK  ] Starting Selenium on the 4444 port ..."
  
install:
  - composer install --dev -vvv
  - cd web
  - drush site-install cucumber --yes --site-name=cucumber --account-name=webmaster --account-pass=dD.123123ddd --db-url=mysql://root:@localhost/cucumber

before_script:
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - sleep 5

script:
  - cd ./profiles/cucumber
  - behat --strict tests/features/cucumber/

matrix:
  fast_finish: true
